import type { ErrorCause, LearningDomain } from "@/domain/learning/contracts";
import type { ReviewedTemplate } from "@/domain/questions/template-schema";

type VariableValue = string | number;

type TemplateInput = Pick<ReviewedTemplate,
  "id" | "skillCode" | "domain" | "difficulty" | "structureTag"
  | "stemPattern" | "answerSpecPattern" | "explanationPattern"
> & {
  variables: Record<string, readonly VariableValue[]>;
  estimatedSeconds?: number;
  readingLoad?: ReviewedTemplate["readingLoad"];
  answerMode?: ReviewedTemplate["answerMode"];
  commonErrors?: ErrorCause[];
  errorTargets?: ReviewedTemplate["errorTargets"];
  hintLadder?: [string, string, string];
  readingCard?: boolean;
};

const regionalIds = new Set([
  "num-estimate-02", "num-reverse-check-02", "geo-spatial-01",
  "data-table-01", "data-bar-01", "data-line-01", "data-compare-01",
  "app-price-02", "app-distance-02", "app-work-02", "app-ratio-02",
  "app-percent-02", "app-multi-step-01", "app-extra-info-01",
  "habit-question-02", "habit-condition-02", "habit-unit-02", "habit-estimate-01",
]);

const transitionIds = new Set([
  "eq-l6-model-03", "geo-composite-01", "app-multi-step-02", "app-extra-info-02",
  "habit-estimate-02", "habit-check-01", "habit-check-02",
]);

const defaultHints: Record<LearningDomain, [string, string, string]> = {
  number_operations: ["先确定运算顺序。", "分步计算，并写下中间结果。", "用逆运算或估算检查答案。"],
  equation_algebra: ["先看未知数在哪一边。", "等式两边要做相同的运算。", "求出未知数后代回原等式检查。"],
  geometry_space: ["先标出已知的长度或角度。", "选择与问题对应的图形公式。", "算完检查单位和图形范围。"],
  data_statistics: ["先读标题、行列和单位。", "只提取问题需要的数据。", "把结果代回表格或图形核对。"],
  application_modeling: ["先圈出问题真正要求的量。", "整理已知条件，再写数量关系。", "分步计算，并用单位和范围检查。"],
  thinking_habits: ["把问题和条件分开读。", "找出有效信息、单位与数量关系。", "用估算或代入说明检查结论。"],
};

const defaultErrors: Record<LearningDomain, ErrorCause[]> = {
  number_operations: ["calculation", "range_check"],
  equation_algebra: ["relationship", "calculation"],
  geometry_space: ["relationship", "missing_unit"],
  data_statistics: ["incomplete_reading", "copied_number"],
  application_modeling: ["incomplete_reading", "relationship", "missing_unit"],
  thinking_habits: ["incomplete_reading", "range_check"],
};

function numberAnswer(unit: string | null = null) {
  return { kind: "number", value: "{{answer}}", tolerance: 0, unit };
}

function choiceAnswer(value: "A" | "B" | "C" | "D") {
  return { kind: "choice", value };
}

function reviewed(input: TemplateInput): ReviewedTemplate {
  const contentTier = transitionIds.has(input.id)
    ? "transition"
    : regionalIds.has(input.id) ? "regional" : "core";
  return {
    id: input.id,
    skillCode: input.skillCode,
    domain: input.domain,
    contentTier,
    difficulty: input.difficulty,
    structureTag: input.structureTag,
    estimatedSeconds: input.estimatedSeconds ?? (30 + input.difficulty * 15),
    readingLoad: input.readingLoad ?? (contentTier === "core" ? "short" : contentTier === "regional" ? "medium" : "long"),
    answerMode: input.answerMode ?? "written",
    stemPattern: input.stemPattern,
    answerSpecPattern: input.answerSpecPattern,
    explanationPattern: input.explanationPattern,
    commonErrors: input.commonErrors ?? defaultErrors[input.domain],
    errorTargets: input.errorTargets,
    hintLadder: input.hintLadder ?? defaultHints[input.domain],
    readingCard: input.readingCard ?? contentTier !== "core",
    source: "original",
    licenseStatus: "owned",
    variantSpec: { variables: input.variables },
  };
}

const catalogInputs: TemplateInput[] = [
  {
    id: "num-int-mental-01", skillCode: "integer-mental", domain: "number_operations",
    difficulty: 1, structureTag: "mental-sum", answerMode: "mental",
    stemPattern: "口算：{{left}} + {{right}} = ？",
    answerSpecPattern: numberAnswer(),
    explanationPattern: "把 {{left}} 拆成整十数和个位数，再与 {{right}} 相加，结果是 {{answer}}。",
    variables: { left: [38, 46, 57], right: [7, 9, 8], answer: [45, 55, 65] },
  },
  {
    id: "num-int-mental-02", skillCode: "integer-mental", domain: "number_operations",
    difficulty: 1, structureTag: "mental-difference", answerMode: "mental",
    stemPattern: "口算：{{left}} - {{right}} = ？",
    answerSpecPattern: numberAnswer(),
    explanationPattern: "先减去整十部分，再调整个位，{{left}} - {{right}} = {{answer}}。",
    variables: { left: [72, 84, 93], right: [18, 27, 36], answer: [54, 57, 57] },
  },
  {
    id: "num-decimal-01", skillCode: "decimal", domain: "number_operations",
    difficulty: 1, structureTag: "decimal-add", answerMode: "written",
    stemPattern: "计算 {{left}} + {{right}}。",
    answerSpecPattern: numberAnswer(),
    explanationPattern: "小数点对齐后逐位相加，得到 {{answer}}。",
    variables: { left: [3.6, 4.25, 7.08], right: [2.4, 1.35, 0.92], answer: [6, 5.6, 8] },
  },
  {
    id: "num-decimal-02", skillCode: "decimal", domain: "number_operations",
    difficulty: 2, structureTag: "decimal-subtract", answerMode: "written",
    stemPattern: "计算 {{left}} - {{right}}。",
    answerSpecPattern: numberAnswer(),
    explanationPattern: "把小数点对齐，不足的数位补零，差是 {{answer}}。",
    variables: { left: [8.5, 12.04, 20.3], right: [3.76, 5.89, 7.45], answer: [4.74, 6.15, 12.85] },
  },
  {
    id: "num-decimal-03", skillCode: "decimal", domain: "number_operations",
    difficulty: 2, structureTag: "decimal-multiply", answerMode: "written",
    stemPattern: "计算 {{left}} × {{right}}。",
    answerSpecPattern: numberAnswer(),
    explanationPattern: "先按整数乘法计算，再根据两个因数的小数位数点小数点，结果是 {{answer}}。",
    variables: { left: [1.2, 2.5, 0.8], right: [3, 4, 7], answer: [3.6, 10, 5.6] },
  },
  {
    id: "num-fraction-01", skillCode: "fraction", domain: "number_operations",
    difficulty: 2, structureTag: "fraction-same-denominator", answerMode: "written",
    stemPattern: "计算 {{expression}}，把结果写成小数。",
    answerSpecPattern: numberAnswer(),
    explanationPattern: "分母相同，只计算分子，再化成小数 {{answer}}。",
    variables: { expression: ["2/5 + 1/5", "3/8 + 2/8", "3/10 + 4/10"], answer: [0.6, 0.625, 0.7] },
  },
  {
    id: "num-fraction-02", skillCode: "fraction", domain: "number_operations",
    difficulty: 2, structureTag: "fraction-unlike-denominator", answerMode: "written",
    stemPattern: "计算 {{expression}}，把结果写成小数。",
    answerSpecPattern: numberAnswer(),
    explanationPattern: "先通分，再合并分子，结果等于 {{answer}}。",
    variables: { expression: ["1/2 + 1/4", "2/3 - 1/6", "3/4 - 2/5"], answer: [0.75, 0.5, 0.35] },
  },
  {
    id: "num-fraction-03", skillCode: "fraction", domain: "number_operations",
    difficulty: 3, structureTag: "fraction-of-quantity", answerMode: "written",
    stemPattern: "求 {{whole}} 的 {{fraction}} 是多少。",
    answerSpecPattern: numberAnswer(),
    explanationPattern: "把总量 {{whole}} 乘对应分数，得到 {{answer}}。",
    variables: { whole: [24, 35, 48], fraction: ["3/4", "2/5", "5/8"], answer: [18, 14, 30] },
  },
  {
    id: "num-mixed-01", skillCode: "mixed-operations", domain: "number_operations",
    difficulty: 2, structureTag: "mixed-order", answerMode: "written",
    stemPattern: "计算 {{expression}}。",
    answerSpecPattern: numberAnswer(),
    explanationPattern: "先算乘除，再算加减，结果是 {{answer}}。",
    variables: { expression: ["18 + 6 × 4", "56 - 24 ÷ 3", "7 × 8 - 19"], answer: [42, 48, 37] },
  },
  {
    id: "num-mixed-02", skillCode: "mixed-operations", domain: "number_operations",
    difficulty: 3, structureTag: "mixed-parentheses", answerMode: "written",
    stemPattern: "计算 {{expression}}。",
    answerSpecPattern: numberAnswer(),
    explanationPattern: "先处理括号，再按运算顺序计算，结果是 {{answer}}。",
    variables: { expression: ["(36 - 12) ÷ 6", "5 × (14 - 8)", "72 ÷ (3 + 5)"], answer: [4, 30, 9] },
  },
  {
    id: "num-law-01", skillCode: "operation-law", domain: "number_operations",
    difficulty: 2, structureTag: "distributive-law", answerMode: "mental",
    stemPattern: "用简便方法计算 {{expression}}。",
    answerSpecPattern: numberAnswer(),
    explanationPattern: "把共同因数提出来，先算括号里的整十数，结果是 {{answer}}。",
    variables: { expression: ["25 × 17 + 25 × 3", "12 × 46 + 12 × 4", "8 × 125 + 8 × 75"], answer: [500, 600, 1600] },
  },
  {
    id: "num-law-02", skillCode: "operation-law", domain: "number_operations",
    difficulty: 2, structureTag: "associative-law", answerMode: "mental",
    stemPattern: "选择合适的运算律计算 {{expression}}。",
    answerSpecPattern: numberAnswer(),
    explanationPattern: "先把能凑整的两个数结合，计算结果是 {{answer}}。",
    variables: { expression: ["37 + 68 + 63", "4 × 25 × 17", "125 × 7 × 8"], answer: [168, 1700, 7000] },
  },
  {
    id: "num-estimate-01", skillCode: "estimate", domain: "number_operations",
    difficulty: 2, structureTag: "estimate-range", answerMode: "choice",
    stemPattern: "不做精确计算，{{expression}} 的结果最接近哪一个？A. {{a}}  B. {{b}}  C. {{c}}  D. {{d}}",
    answerSpecPattern: choiceAnswer("B"),
    explanationPattern: "把两个数分别看作接近的整十或整数，估算结果接近选项 B。",
    commonErrors: ["incomplete_reading", "range_check"],
    errorTargets: { incompleteReading: ["A", "C", "D"] },
    variables: { expression: ["198 + 304", "49.8 × 6.1", "803 - 397"], a: [400, 250, 300], b: [500, 300, 400], c: [600, 350, 500], d: [700, 400, 600] },
  },
  {
    id: "num-estimate-02", skillCode: "estimate", domain: "number_operations",
    difficulty: 3, structureTag: "estimate-explain", answerMode: "choice", readingCard: true,
    stemPattern: "小宁估算 {{expression}} 时说结果约为 {{claim}}。结合数量级判断，哪项说明最合理？A. 一定偏大  B. 估算合理  C. 一定偏小  D. 无法比较",
    answerSpecPattern: choiceAnswer("B"),
    explanationPattern: "先看每个数的数量级和接近的整值；信息显示 {{claim}} 与合理范围一致，所以数量关系支持 B。",
    variables: { expression: ["297 × 21", "62.4 ÷ 3.1", "398 + 605 + 97"], claim: ["6000", "20", "1100"] },
  },
  {
    id: "num-reverse-check-01", skillCode: "reverse-check", domain: "number_operations",
    difficulty: 2, structureTag: "inverse-check", answerMode: "choice",
    stemPattern: "算式 {{expression}} 的结果是 {{claim}}。下面哪一个算式能直接检查这个结果？A. {{a}}  B. {{b}}  C. {{c}}  D. {{d}}",
    answerSpecPattern: choiceAnswer("C"),
    explanationPattern: "用对应的逆运算把结果还原到原数，选项 C 能完成检查。",
    variables: { expression: ["84 - 37", "6.4 + 2.8", "15 × 7"], claim: [47, 9.2, 105], a: ["84 + 37", "6.4 - 2.8", "15 + 7"], b: ["47 - 37", "9.2 + 2.8", "105 × 7"], c: ["47 + 37", "9.2 - 2.8", "105 ÷ 7"], d: ["84 + 47", "9.2 + 6.4", "105 - 15"] },
  },
  {
    id: "num-reverse-check-02", skillCode: "reverse-check", domain: "number_operations",
    difficulty: 3, structureTag: "error-analysis", answerMode: "choice", readingCard: true,
    stemPattern: "同学计算 {{expression}} 得到 {{claim}}，又用 {{check}} 检查。根据两条信息，最合理的判断是：A. 原计算一定正确  B. 检查式与原式无关  C. 检查发现原结果有误  D. 只需改单位",
    answerSpecPattern: choiceAnswer("C"),
    explanationPattern: "检查式应还原原来的数量关系；代入 {{claim}} 后信息不成立，因此原结果有误，应选 C。",
    variables: { expression: ["72 ÷ 8", "13.5 - 4.7", "28 × 6"], claim: [8, 9.8, 158], check: ["8 × 8 是否等于 72", "9.8 + 4.7 是否等于 13.5", "158 ÷ 6 是否等于 28"] },
  },
  {
    id: "num-int-mental-03", skillCode: "integer-mental", domain: "number_operations",
    difficulty: 2, structureTag: "mental-sum", answerMode: "mental",
    stemPattern: "口算：{{left}} + {{right}} = ？",
    answerSpecPattern: numberAnswer(),
    explanationPattern: "把 {{left}} 拆成整十数和个位数，再与 {{right}} 相加，结果是 {{answer}}。",
    variables: { left: [125, 238, 347], right: [37, 42, 56], answer: [162, 280, 403] },
  },
  {
    id: "num-decimal-04", skillCode: "decimal", domain: "number_operations",
    difficulty: 3, structureTag: "decimal-divide", answerMode: "written",
    stemPattern: "计算 {{left}} ÷ {{right}}。",
    answerSpecPattern: numberAnswer(),
    explanationPattern: "小数除法先把除数化成整数，再按除法计算，结果是 {{answer}}。",
    variables: { left: [7.2, 12.6, 18.9], right: [0.9, 1.4, 2.1], answer: [8, 9, 9] },
  },
  {
    id: "num-fraction-04", skillCode: "fraction", domain: "number_operations",
    difficulty: 3, structureTag: "fraction-multiply", answerMode: "written",
    stemPattern: "计算 {{expression}}，把结果写成小数。",
    answerSpecPattern: numberAnswer(),
    explanationPattern: "先约分或通分，再完成分数运算，结果等于 {{answer}}。",
    variables: { expression: ["2/3 × 3/4", "5/6 - 1/3", "7/10 + 1/5"], answer: [0.5, 0.5, 0.9] },
  },
  {
    id: "num-mixed-03", skillCode: "mixed-operations", domain: "number_operations",
    difficulty: 3, structureTag: "mixed-parentheses", answerMode: "written",
    stemPattern: "计算 {{expression}}。",
    answerSpecPattern: numberAnswer(),
    explanationPattern: "先处理括号，再按运算顺序计算，结果是 {{answer}}。",
    variables: { expression: ["(48 + 12) ÷ 5", "6 × (18 - 9) + 4", "90 - (24 + 16) ÷ 8"], answer: [12, 58, 85] },
  },
  {
    id: "num-law-03", skillCode: "operation-law", domain: "number_operations",
    difficulty: 3, structureTag: "distributive-law", answerMode: "mental",
    stemPattern: "用简便方法计算 {{expression}}。",
    answerSpecPattern: numberAnswer(),
    explanationPattern: "把共同因数提出来，先算括号里的整十数，结果是 {{answer}}。",
    variables: { expression: ["37 × 19 + 37", "24 × 49 + 24", "125 × 32 + 125 × 8"], answer: [740, 1200, 5000] },
  },
  {
    id: "num-estimate-03", skillCode: "estimate", domain: "number_operations",
    difficulty: 3, structureTag: "estimate-range", answerMode: "choice",
    stemPattern: "不做精确计算，{{expression}} 的结果最接近哪一个？A. {{a}}  B. {{b}}  C. {{c}}  D. {{d}}",
    answerSpecPattern: choiceAnswer("B"),
    explanationPattern: "把两个数分别看作接近的整十或整数，估算结果接近选项 B。",
    variables: { expression: ["398 + 205", "29.8 × 4.1", "902 - 498"], a: [400, 80, 300], b: [600, 120, 400], c: [800, 160, 500], d: [1000, 200, 600] },
  },
  {
    id: "num-reverse-check-03", skillCode: "reverse-check", domain: "number_operations",
    difficulty: 3, structureTag: "inverse-check", answerMode: "choice",
    stemPattern: "算式 {{expression}} 的结果是 {{claim}}。下面哪一个算式能直接检查这个结果？A. {{a}}  B. {{b}}  C. {{c}}  D. {{d}}",
    answerSpecPattern: choiceAnswer("C"),
    explanationPattern: "用对应的逆运算把结果还原到原数，选项 C 能完成检查。",
    variables: { expression: ["96 - 38", "7.2 + 4.8", "18 × 6"], claim: [58, 12, 108], a: ["96 + 38", "7.2 - 4.8", "18 + 6"], b: ["58 - 38", "12 + 4.8", "108 × 6"], c: ["58 + 38", "12 - 7.2", "108 ÷ 6"], d: ["96 + 58", "12 + 7.2", "108 - 18"] },
  },

  {
    id: "eq-l1-balance-01", skillCode: "equation-l1", domain: "equation_algebra",
    difficulty: 1, structureTag: "equation-direct", answerMode: "equation",
    stemPattern: "解方程：x + {{addend}} = {{total}}。",
    answerSpecPattern: numberAnswer(),
    explanationPattern: "等式两边同时减去 {{addend}}，得到 x = {{answer}}。",
    variables: { addend: [4, 7, 9], total: [13, 19, 24], answer: [9, 12, 15] },
  },
  {
    id: "eq-l1-balance-02", skillCode: "equation-l1", domain: "equation_algebra",
    difficulty: 1, structureTag: "equation-step", answerMode: "choice",
    stemPattern: "方程 x + {{addend}} = {{total}} 的第一步应怎样做？A. 两边加 {{addend}}  B. 两边减 {{addend}}  C. 两边乘 {{addend}}  D. 只把左边减 {{addend}}",
    answerSpecPattern: choiceAnswer("B"),
    explanationPattern: "保持等式平衡，必须在两边同时减去 {{addend}}。",
    variables: { addend: [5, 8, 11], total: [17, 21, 30] },
  },
  {
    id: "eq-l1-balance-03", skillCode: "equation-l1", domain: "equation_algebra",
    difficulty: 1, structureTag: "equation-model-check", answerMode: "choice",
    stemPattern: "盒中原有 x 枚棋子，又放入 {{addend}} 枚后共有 {{total}} 枚。哪一个方程正确？A. x - {{addend}} = {{total}}  B. x + {{addend}} = {{total}}  C. {{addend}}x = {{total}}  D. x = {{addend}} + {{total}}",
    answerSpecPattern: choiceAnswer("B"),
    explanationPattern: "原有数量加上放入数量等于总数，数量关系是 x + {{addend}} = {{total}}。",
    variables: { addend: [6, 9, 12], total: [18, 25, 31] },
  },
  {
    id: "eq-l2-add-sub-01", skillCode: "equation-l2", domain: "equation_algebra",
    difficulty: 1, structureTag: "equation-direct", answerMode: "equation",
    stemPattern: "解方程：x - {{subtrahend}} = {{remaining}}。",
    answerSpecPattern: numberAnswer(),
    explanationPattern: "等式两边同时加 {{subtrahend}}，得到 x = {{answer}}。",
    variables: { subtrahend: [5, 8, 13], remaining: [13, 17, 21], answer: [18, 25, 34] },
  },
  {
    id: "eq-l2-add-sub-02", skillCode: "equation-l2", domain: "equation_algebra",
    difficulty: 2, structureTag: "equation-step", answerMode: "choice",
    stemPattern: "解 x - {{subtrahend}} = {{remaining}} 时，小禾写成 x = {{remaining}} - {{subtrahend}}。应如何判断？A. 正确  B. 应把两数相加  C. 应把两数相乘  D. 只需交换等号两边",
    answerSpecPattern: choiceAnswer("B"),
    explanationPattern: "为了抵消减去的 {{subtrahend}}，等式两边要同时加 {{subtrahend}}，所以应相加。",
    variables: { subtrahend: [6, 9, 14], remaining: [12, 20, 25] },
  },
  {
    id: "eq-l2-add-sub-03", skillCode: "equation-l2", domain: "equation_algebra",
    difficulty: 2, structureTag: "equation-model-check", answerMode: "equation",
    stemPattern: "某数加 {{added}} 后是 {{total}}。列方程 x + {{added}} = {{total}} 并求 x。",
    answerSpecPattern: numberAnswer(),
    explanationPattern: "总数减去增加的 {{added}}，得到原数 {{answer}}；代入方程后等号两边相等。",
    variables: { added: [7, 12, 18], total: [24, 35, 50], answer: [17, 23, 32] },
  },
  {
    id: "eq-l3-mul-div-01", skillCode: "equation-l3", domain: "equation_algebra",
    difficulty: 2, structureTag: "equation-direct", answerMode: "equation",
    stemPattern: "解方程：{{coefficient}}x = {{total}}。",
    answerSpecPattern: numberAnswer(),
    explanationPattern: "等式两边同时除以 {{coefficient}}，得到 x = {{answer}}。",
    variables: { coefficient: [3, 4, 6], total: [27, 48, 90], answer: [9, 12, 15] },
  },
  {
    id: "eq-l3-mul-div-02", skillCode: "equation-l3", domain: "equation_algebra",
    difficulty: 2, structureTag: "equation-step", answerMode: "choice",
    stemPattern: "方程 {{coefficient}}x = {{total}} 中，下一步应写成：A. x = {{total}} + {{coefficient}}  B. x = {{total}} - {{coefficient}}  C. x = {{total}} ÷ {{coefficient}}  D. x = {{total}} × {{coefficient}}",
    answerSpecPattern: choiceAnswer("C"),
    explanationPattern: "{{coefficient}} 与 x 相乘，应用除法逆运算，所以选 C。",
    variables: { coefficient: [5, 7, 8], total: [40, 63, 96] },
  },
  {
    id: "eq-l3-mul-div-03", skillCode: "equation-l3", domain: "equation_algebra",
    difficulty: 2, structureTag: "equation-model-check", answerMode: "equation",
    stemPattern: "把一个数平均分成 {{divisor}} 份，每份是 {{quotient}}。用 x ÷ {{divisor}} = {{quotient}} 表示并求 x。",
    answerSpecPattern: numberAnswer(),
    explanationPattern: "每份数乘份数得到总数，x = {{quotient}} × {{divisor}} = {{answer}}。",
    variables: { divisor: [3, 5, 8], quotient: [7, 9, 12], answer: [21, 45, 96] },
  },
  {
    id: "eq-l4-two-step-01", skillCode: "equation-l4", domain: "equation_algebra",
    difficulty: 3, structureTag: "equation-direct", answerMode: "equation",
    stemPattern: "解方程：{{coefficient}}x + {{offset}} = {{right}}。",
    answerSpecPattern: numberAnswer(),
    explanationPattern: "先在等式两边减去 {{offset}}，再除以 {{coefficient}}，得到 x = {{answer}}。",
    variables: { coefficient: [2, 3, 4], offset: [5, 7, 9], right: [23, 34, 45], answer: [9, 9, 9] },
  },
  {
    id: "eq-l4-two-step-02", skillCode: "equation-l4", domain: "equation_algebra",
    difficulty: 3, structureTag: "equation-step", answerMode: "choice",
    stemPattern: "解 {{coefficient}}x + {{offset}} = {{right}} 时，哪组步骤保持等式平衡？A. 先除以 {{coefficient}}，再减 {{offset}}  B. 先两边减 {{offset}}，再两边除以 {{coefficient}}  C. 只把左边减 {{offset}}  D. 两边先加 {{offset}}",
    answerSpecPattern: choiceAnswer("B"),
    explanationPattern: "先消去常数项，再消去 x 的系数；每一步都要在等式两边同时进行。",
    variables: { coefficient: [2, 4, 5], offset: [3, 7, 10], right: [19, 39, 60] },
  },
  {
    id: "eq-l4-two-step-03", skillCode: "equation-l4", domain: "equation_algebra",
    difficulty: 3, structureTag: "equation-model-check", answerMode: "equation",
    stemPattern: "每盒彩笔 {{coefficient}} 支，另有散装 {{offset}} 支，共 {{right}} 支。列方程 {{coefficient}}x + {{offset}} = {{right}}，求盒数 x。",
    answerSpecPattern: numberAnswer("盒"),
    explanationPattern: "先从总数中去掉散装的 {{offset}} 支，再按每盒 {{coefficient}} 支平均分，得到 {{answer}} 盒。",
    variables: { coefficient: [6, 8, 12], offset: [3, 5, 7], right: [39, 61, 103], answer: [6, 7, 8] },
  },
  {
    id: "eq-l5-complex-01", skillCode: "equation-l5", domain: "equation_algebra",
    difficulty: 3, structureTag: "equation-direct", answerMode: "equation",
    stemPattern: "解方程：{{factor}}(x + {{offset}}) = {{right}}。",
    answerSpecPattern: numberAnswer(),
    explanationPattern: "先把等式两边除以 {{factor}}，再减去 {{offset}}，得到 x = {{answer}}。",
    variables: { factor: [3, 4, 5], offset: [2, 3, 4], right: [33, 52, 80], answer: [9, 10, 12] },
  },
  {
    id: "eq-l5-complex-02", skillCode: "equation-l5", domain: "equation_algebra",
    difficulty: 3, structureTag: "equation-step", answerMode: "choice",
    stemPattern: "方程 {{factor}}(x - {{offset}}) = {{right}} 展开后应是：A. {{factor}}x - {{offset}} = {{right}}  B. {{factor}}x - {{product}} = {{right}}  C. x - {{product}} = {{right}}  D. {{factor}}x + {{product}} = {{right}}",
    answerSpecPattern: choiceAnswer("B"),
    explanationPattern: "乘法分配到括号内两项，{{factor}} × {{offset}} = {{product}}，所以选 B。",
    variables: { factor: [3, 4, 6], offset: [2, 5, 3], product: [6, 20, 18], right: [21, 28, 42] },
  },
  {
    id: "eq-l5-complex-03", skillCode: "equation-l5", domain: "equation_algebra",
    difficulty: 4, structureTag: "equation-model-check", answerMode: "equation",
    stemPattern: "解方程：(x - {{offset}}) ÷ {{divisor}} = {{quotient}}。",
    answerSpecPattern: numberAnswer(),
    explanationPattern: "先把等式两边乘 {{divisor}}，再加 {{offset}}，得到 x = {{answer}}；代回原式可核对。",
    variables: { offset: [4, 7, 9], divisor: [3, 5, 6], quotient: [6, 4, 8], answer: [22, 27, 57] },
  },
  {
    id: "eq-l6-model-01", skillCode: "equation-l6", domain: "equation_algebra",
    difficulty: 4, structureTag: "equation-direct", answerMode: "equation",
    stemPattern: "解方程：{{leftFactor}}x + {{leftOffset}} = {{rightFactor}}x + {{rightOffset}}。",
    answerSpecPattern: numberAnswer(),
    explanationPattern: "把含 x 的项移到一边、常数项移到另一边，化简后 x = {{answer}}。",
    variables: { leftFactor: [3, 5, 7], leftOffset: [4, 6, 8], rightFactor: [2, 3, 4], rightOffset: [12, 24, 35], answer: [8, 9, 9] },
  },
  {
    id: "eq-l6-model-02", skillCode: "equation-l6", domain: "equation_algebra",
    difficulty: 4, structureTag: "equation-step", answerMode: "choice",
    stemPattern: "检查方程 {{leftFactor}}x + {{leftOffset}} = {{rightFactor}}x + {{rightOffset}} 的解 x = {{claim}}，应优先做什么？A. 只算左边  B. 把 {{claim}} 分别代入等号两边  C. 把所有数相加  D. 改写题目条件",
    answerSpecPattern: choiceAnswer("B"),
    explanationPattern: "检验方程的解要把同一个数代入等号两边，比较两边是否相等。",
    variables: { leftFactor: [4, 6, 8], leftOffset: [3, 5, 7], rightFactor: [2, 3, 5], rightOffset: [17, 26, 34], claim: [7, 7, 9] },
  },
  {
    id: "eq-l6-model-03", skillCode: "equation-l6", domain: "equation_algebra",
    difficulty: 4, structureTag: "equation-model-check", answerMode: "equation", readingCard: true,
    stemPattern: "两种装盒方案数量相同：方案甲每组 {{factor}} 盒并另加括号内的 {{add}} 盒，方案乙有 {{other}}x 盒再加 {{total}} 盒。根据 {{factor}}(x + {{add}}) = {{other}}x + {{total}} 求 x。",
    answerSpecPattern: numberAnswer(),
    explanationPattern: "先按分配律整理两边，再保持等式平衡合并同类项；数量关系给出唯一解 x = {{answer}}。",
    variables: { factor: [3, 4, 5], add: [2, 1, 2], other: [1, 2, 3], total: [14, 16, 24], answer: [4, 6, 7] },
  },
  {
    id: "eq-l1-balance-04", skillCode: "equation-l1", domain: "equation_algebra",
    difficulty: 1, structureTag: "equation-direct", answerMode: "equation",
    stemPattern: "解方程：x + {{addend}} = {{total}}。",
    answerSpecPattern: numberAnswer(),
    explanationPattern: "等式两边同时减去 {{addend}}，得到 x = {{answer}}。",
    variables: { addend: [6, 12, 15], total: [20, 31, 40], answer: [14, 19, 25] },
  },
  {
    id: "eq-l2-add-sub-04", skillCode: "equation-l2", domain: "equation_algebra",
    difficulty: 2, structureTag: "equation-step", answerMode: "choice",
    stemPattern: "解 x - {{subtrahend}} = {{remaining}} 时，小禾写成 x = {{remaining}} - {{subtrahend}}。应如何判断？A. 正确  B. 应把两数相加  C. 应把两数相乘  D. 只需交换等号两边",
    answerSpecPattern: choiceAnswer("B"),
    explanationPattern: "为了抵消减去的 {{subtrahend}}，等式两边要同时加 {{subtrahend}}，所以应相加。",
    variables: { subtrahend: [4, 7, 15], remaining: [11, 18, 26] },
  },
  {
    id: "eq-l3-mul-div-04", skillCode: "equation-l3", domain: "equation_algebra",
    difficulty: 2, structureTag: "equation-direct", answerMode: "equation",
    stemPattern: "解方程：{{coefficient}}x = {{total}}。",
    answerSpecPattern: numberAnswer(),
    explanationPattern: "等式两边同时除以 {{coefficient}}，得到 x = {{answer}}。",
    variables: { coefficient: [3, 5, 7], total: [36, 55, 84], answer: [12, 11, 12] },
  },
  {
    id: "eq-l4-two-step-04", skillCode: "equation-l4", domain: "equation_algebra",
    difficulty: 3, structureTag: "equation-step", answerMode: "choice",
    stemPattern: "解 {{coefficient}}x + {{offset}} = {{right}} 时，哪组步骤保持等式平衡？A. 先除以 {{coefficient}}，再减 {{offset}}  B. 先两边减 {{offset}}，再两边除以 {{coefficient}}  C. 只把左边减 {{offset}}  D. 两边先加 {{offset}}",
    answerSpecPattern: choiceAnswer("B"),
    explanationPattern: "先消去常数项，再消去 x 的系数；每一步都要在等式两边同时进行。",
    variables: { coefficient: [3, 5, 6], offset: [4, 8, 9], right: [25, 43, 51] },
  },
  {
    id: "eq-l5-complex-04", skillCode: "equation-l5", domain: "equation_algebra",
    difficulty: 4, structureTag: "equation-direct", answerMode: "equation",
    stemPattern: "解方程：{{factor}}(x + {{offset}}) = {{right}}。",
    answerSpecPattern: numberAnswer(),
    explanationPattern: "先把等式两边除以 {{factor}}，再减去 {{offset}}，得到 x = {{answer}}。",
    variables: { factor: [2, 3, 6], offset: [5, 4, 3], right: [34, 39, 66], answer: [12, 9, 8] },
  },
  {
    id: "eq-l6-model-04", skillCode: "equation-l6", domain: "equation_algebra",
    difficulty: 4, structureTag: "equation-step", answerMode: "choice",
    stemPattern: "检查方程 {{leftFactor}}x + {{leftOffset}} = {{rightFactor}}x + {{rightOffset}} 的解 x = {{claim}}，应优先做什么？A. 只算左边  B. 把 {{claim}} 分别代入等号两边  C. 把所有数相加  D. 改写题目条件",
    answerSpecPattern: choiceAnswer("B"),
    explanationPattern: "检验方程的解要把同一个数代入等号两边，比较两边是否相等。",
    variables: { leftFactor: [3, 5, 7], leftOffset: [4, 6, 8], rightFactor: [2, 3, 4], rightOffset: [14, 26, 35], claim: [10, 10, 9] },
  },
  {
    id: "eq-l6-model-05", skillCode: "equation-l6", domain: "equation_algebra",
    difficulty: 4, structureTag: "equation-model-check", answerMode: "equation", readingCard: true,
    stemPattern: "两种装盒方案数量相同：方案甲每组 {{factor}} 盒并另加括号内的 {{add}} 盒，方案乙有 {{other}}x 盒再加 {{total}} 盒。根据 {{factor}}(x + {{add}}) = {{other}}x + {{total}} 求 x。",
    answerSpecPattern: numberAnswer(),
    explanationPattern: "先按分配律整理两边，再保持等式平衡合并同类项；数量关系给出唯一解 x = {{answer}}。",
    variables: { factor: [2, 3, 4], add: [3, 2, 1], other: [1, 2, 3], total: [11, 14, 16], answer: [5, 8, 12] },
  },

  {
    id: "geo-angle-01", skillCode: "angle", domain: "geometry_space",
    difficulty: 2, structureTag: "angle-supplement", answerMode: "written",
    stemPattern: "一个平角被分成两个角，其中一个是 {{known}} 度，另一个是多少度？",
    answerSpecPattern: numberAnswer("度"),
    explanationPattern: "平角是 180 度，用 180 - {{known}}，得到 {{answer}} 度。",
    variables: { known: [65, 78, 112], answer: [115, 102, 68] },
  },
  {
    id: "geo-perimeter-01", skillCode: "perimeter", domain: "geometry_space",
    difficulty: 2, structureTag: "rectangle-perimeter", answerMode: "written",
    stemPattern: "长方形长 {{length}} 厘米，宽 {{width}} 厘米，周长是多少厘米？",
    answerSpecPattern: numberAnswer("厘米"),
    explanationPattern: "周长是两条长与两条宽的和，2 × ({{length}} + {{width}}) = {{answer}} 厘米。",
    variables: { length: [8, 12, 15], width: [5, 7, 9], answer: [26, 38, 48] },
  },
  {
    id: "geo-perimeter-02", skillCode: "perimeter", domain: "geometry_space",
    difficulty: 3, structureTag: "missing-side-perimeter", answerMode: "written",
    stemPattern: "一个长方形周长 {{perimeter}} 厘米，长 {{length}} 厘米，宽是多少厘米？",
    answerSpecPattern: numberAnswer("厘米"),
    explanationPattern: "先用周长除以 2 得到长宽和，再减去长，宽是 {{answer}} 厘米。",
    variables: { perimeter: [34, 50, 68], length: [11, 16, 22], answer: [6, 9, 12] },
  },
  {
    id: "geo-area-01", skillCode: "area", domain: "geometry_space",
    difficulty: 2, structureTag: "rectangle-area", answerMode: "written",
    stemPattern: "长方形长 {{length}} 厘米，宽 {{width}} 厘米，面积是多少平方厘米？",
    answerSpecPattern: numberAnswer("平方厘米"),
    explanationPattern: "长方形面积等于长乘宽，{{length}} × {{width}} = {{answer}} 平方厘米。",
    variables: { length: [9, 12, 15], width: [4, 7, 8], answer: [36, 84, 120] },
  },
  {
    id: "geo-area-02", skillCode: "area", domain: "geometry_space",
    difficulty: 3, structureTag: "triangle-area", answerMode: "written",
    stemPattern: "三角形底 {{base}} 厘米，高 {{height}} 厘米，面积是多少平方厘米？",
    answerSpecPattern: numberAnswer("平方厘米"),
    explanationPattern: "三角形面积等于底乘高再除以 2，结果是 {{answer}} 平方厘米。",
    variables: { base: [8, 12, 15], height: [5, 7, 8], answer: [20, 42, 60] },
  },
  {
    id: "geo-volume-01", skillCode: "volume", domain: "geometry_space",
    difficulty: 3, structureTag: "cuboid-volume", answerMode: "written",
    stemPattern: "长方体长 {{length}} 厘米、宽 {{width}} 厘米、高 {{height}} 厘米，体积是多少立方厘米？",
    answerSpecPattern: numberAnswer("立方厘米"),
    explanationPattern: "长方体体积等于长乘宽乘高，结果是 {{answer}} 立方厘米。",
    variables: { length: [6, 8, 10], width: [4, 5, 6], height: [3, 4, 5], answer: [72, 160, 300] },
  },
  {
    id: "geo-composite-01", skillCode: "composite-geometry", domain: "geometry_space",
    difficulty: 4, structureTag: "composite-area", answerMode: "written", readingCard: true,
    stemPattern: "一块 L 形纸板可看成 {{outerLength}} 厘米 × {{outerWidth}} 厘米的长方形，挖去一个 {{cutLength}} 厘米 × {{cutWidth}} 厘米的小长方形。剩余面积是多少平方厘米？",
    answerSpecPattern: numberAnswer("平方厘米"),
    explanationPattern: "先算外部长方形面积，再减去挖去部分；两块信息对应的数量关系给出 {{answer}} 平方厘米。",
    variables: { outerLength: [12, 15, 18], outerWidth: [9, 10, 12], cutLength: [4, 5, 6], cutWidth: [3, 4, 5], answer: [96, 130, 186] },
  },
  {
    id: "geo-spatial-01", skillCode: "spatial", domain: "geometry_space",
    difficulty: 3, structureTag: "spatial-view", answerMode: "choice", readingCard: true,
    stemPattern: "用 {{count}} 个相同小正方体排成一列，再在从左数第 {{position}} 个上方叠 1 个。从正面看，各列高度最合理的是：A. {{a}}  B. {{b}}  C. {{c}}  D. {{d}}",
    answerSpecPattern: choiceAnswer("C"),
    explanationPattern: "先把每列作为一条信息：只有第 {{position}} 列高度为 2，其余列高度为 1，所以数量关系对应 C。",
    variables: { count: [4, 5, 6], position: [2, 3, 4], a: ["2,1,1,1", "1,2,1,1,1", "1,1,2,1,1,1"], b: ["1,1,2,1", "1,1,1,2,1", "1,1,1,1,2,1"], c: ["1,2,1,1", "1,1,2,1,1", "1,1,1,2,1,1"], d: ["1,1,1,2", "2,1,1,1,1", "2,1,1,1,1,1"] },
  },
  {
    id: "geo-angle-02", skillCode: "angle", domain: "geometry_space",
    difficulty: 1, structureTag: "angle-supplement", answerMode: "written",
    stemPattern: "一个平角被分成两个角，其中一个是 {{known}} 度，另一个是多少度？",
    answerSpecPattern: numberAnswer("度"),
    explanationPattern: "平角是 180 度，用 180 - {{known}}，得到 {{answer}} 度。",
    variables: { known: [35, 96, 128], answer: [145, 84, 52] },
  },
  {
    id: "geo-angle-03", skillCode: "angle", domain: "geometry_space",
    difficulty: 3, structureTag: "angle-supplement", answerMode: "written",
    stemPattern: "一个平角被分成两个角，其中一个是 {{known}} 度，另一个是多少度？",
    answerSpecPattern: numberAnswer("度"),
    explanationPattern: "平角是 180 度，用 180 - {{known}}，得到 {{answer}} 度。",
    variables: { known: [42.5, 107.5, 156], answer: [137.5, 72.5, 24] },
  },
  {
    id: "geo-perimeter-03", skillCode: "perimeter", domain: "geometry_space",
    difficulty: 2, structureTag: "rectangle-perimeter", answerMode: "written",
    stemPattern: "长方形长 {{length}} 厘米，宽 {{width}} 厘米，周长是多少厘米？",
    answerSpecPattern: numberAnswer("厘米"),
    explanationPattern: "周长是两条长与两条宽的和，2 × ({{length}} + {{width}}) = {{answer}} 厘米。",
    variables: { length: [18, 24, 31], width: [7, 9, 12], answer: [50, 66, 86] },
  },
  {
    id: "geo-perimeter-04", skillCode: "perimeter", domain: "geometry_space",
    difficulty: 3, structureTag: "missing-side-perimeter", answerMode: "written",
    stemPattern: "一个长方形周长 {{perimeter}} 厘米，长 {{length}} 厘米，宽是多少厘米？",
    answerSpecPattern: numberAnswer("厘米"),
    explanationPattern: "先用周长除以 2 得到长宽和，再减去长，宽是 {{answer}} 厘米。",
    variables: { perimeter: [44, 62, 80], length: [15, 21, 28], answer: [7, 10, 12] },
  },
  {
    id: "geo-area-03", skillCode: "area", domain: "geometry_space",
    difficulty: 2, structureTag: "rectangle-area", answerMode: "written",
    stemPattern: "长方形长 {{length}} 厘米，宽 {{width}} 厘米，面积是多少平方厘米？",
    answerSpecPattern: numberAnswer("平方厘米"),
    explanationPattern: "长方形面积等于长乘宽，{{length}} × {{width}} = {{answer}} 平方厘米。",
    variables: { length: [16, 23, 28], width: [5, 6, 9], answer: [80, 138, 252] },
  },
  {
    id: "geo-area-04", skillCode: "area", domain: "geometry_space",
    difficulty: 4, structureTag: "triangle-area", answerMode: "written",
    stemPattern: "三角形底 {{base}} 厘米，高 {{height}} 厘米，面积是多少平方厘米？",
    answerSpecPattern: numberAnswer("平方厘米"),
    explanationPattern: "三角形面积等于底乘高再除以 2，结果是 {{answer}} 平方厘米。",
    variables: { base: [14, 18, 25], height: [9, 12, 16], answer: [63, 108, 200] },
  },
  {
    id: "geo-volume-02", skillCode: "volume", domain: "geometry_space",
    difficulty: 2, structureTag: "cuboid-volume", answerMode: "written",
    stemPattern: "长方体长 {{length}} 厘米、宽 {{width}} 厘米、高 {{height}} 厘米，体积是多少立方厘米？",
    answerSpecPattern: numberAnswer("立方厘米"),
    explanationPattern: "长方体体积等于长乘宽乘高，结果是 {{answer}} 立方厘米。",
    variables: { length: [5, 7, 9], width: [3, 4, 5], height: [2, 3, 4], answer: [30, 84, 180] },
  },
  {
    id: "geo-volume-03", skillCode: "volume", domain: "geometry_space",
    difficulty: 4, structureTag: "cuboid-volume", answerMode: "written",
    stemPattern: "长方体长 {{length}} 厘米、宽 {{width}} 厘米、高 {{height}} 厘米，体积是多少立方厘米？",
    answerSpecPattern: numberAnswer("立方厘米"),
    explanationPattern: "长方体体积等于长乘宽乘高，结果是 {{answer}} 立方厘米。",
    variables: { length: [12, 15, 18], width: [8, 9, 10], height: [6, 7, 8], answer: [576, 945, 1440] },
  },
  {
    id: "geo-composite-02", skillCode: "composite-geometry", domain: "geometry_space",
    difficulty: 4, structureTag: "composite-area", answerMode: "written", readingCard: true,
    stemPattern: "一块 L 形纸板可看成 {{outerLength}} 厘米 × {{outerWidth}} 厘米的长方形，挖去一个 {{cutLength}} 厘米 × {{cutWidth}} 厘米的小长方形。剩余面积是多少平方厘米？",
    answerSpecPattern: numberAnswer("平方厘米"),
    explanationPattern: "先算外部长方形面积，再减去挖去部分；两块信息对应的数量关系给出 {{answer}} 平方厘米。",
    variables: { outerLength: [20, 24, 30], outerWidth: [14, 16, 18], cutLength: [5, 6, 8], cutWidth: [4, 5, 6], answer: [260, 354, 492] },
  },
  {
    id: "geo-spatial-02", skillCode: "spatial", domain: "geometry_space",
    difficulty: 4, structureTag: "spatial-view", answerMode: "choice", readingCard: true,
    stemPattern: "用 {{count}} 个相同小正方体排成一列，再在从左数第 {{position}} 个上方叠 1 个。从正面看，各列高度最合理的是：A. {{a}}  B. {{b}}  C. {{c}}  D. {{d}}",
    answerSpecPattern: choiceAnswer("C"),
    explanationPattern: "先把每列作为一条信息：只有第 {{position}} 列高度为 2，其余列高度为 1，所以数量关系对应 C。",
    variables: { count: [3, 4, 5], position: [2, 3, 4], a: ["2,1,1", "1,2,1,1", "1,1,2,1,1"], b: ["1,1,2", "1,1,1,2", "1,1,1,1,2"], c: ["1,2,1", "1,1,2,1", "1,1,1,2,1"], d: ["1,1,1", "2,1,1,1", "2,1,1,1,1"] },
  },

  {
    id: "data-table-01", skillCode: "data-table", domain: "data_statistics",
    difficulty: 2, structureTag: "table-multi-read", answerMode: "written", readingCard: true,
    stemPattern: "阅读记录：甲组 {{aMorning}} 人上午参加、{{aAfternoon}} 人下午参加；乙组 {{bMorning}} 人上午参加、{{bAfternoon}} 人下午参加。两组下午参加的总人数是多少人？",
    answerSpecPattern: numberAnswer("人"),
    explanationPattern: "题目只要下午这一列的信息，数量关系是 {{aAfternoon}} + {{bAfternoon}} = {{answer}} 人。",
    variables: { aMorning: [12, 15, 18], aAfternoon: [9, 11, 14], bMorning: [10, 13, 17], bAfternoon: [8, 12, 15], answer: [17, 23, 29] },
  },
  {
    id: "data-bar-01", skillCode: "data-bar", domain: "data_statistics",
    difficulty: 2, structureTag: "bar-compare", answerMode: "written", readingCard: true,
    stemPattern: "条形图文字记录显示：一班回收 {{first}} 千克，二班回收 {{second}} 千克，三班回收 {{third}} 千克。最多的班比最少的班多多少千克？",
    answerSpecPattern: numberAnswer("千克"),
    explanationPattern: "先从三条信息中找最大值和最小值，再相减，数量关系得到 {{answer}} 千克。",
    variables: { first: [18, 24, 31], second: [25, 19, 27], third: [21, 29, 36], answer: [7, 10, 9] },
  },
  {
    id: "data-line-01", skillCode: "data-line", domain: "data_statistics",
    difficulty: 3, structureTag: "line-change", answerMode: "written", readingCard: true,
    stemPattern: "折线记录中，周一为 {{monday}} 页，周二为 {{tuesday}} 页，周三为 {{wednesday}} 页。周一到周三一共增加了多少页？",
    answerSpecPattern: numberAnswer("页"),
    explanationPattern: "问题比较起点和终点，不必把每天变化相加；用周三信息减周一信息，得到 {{answer}} 页。",
    variables: { monday: [12, 18, 25], tuesday: [17, 21, 32], wednesday: [23, 30, 39], answer: [11, 12, 14] },
  },
  {
    id: "data-average-01", skillCode: "data-average", domain: "data_statistics",
    difficulty: 3, structureTag: "average", answerMode: "written",
    stemPattern: "四次练习得分依次为 {{scores}} 分，平均分是多少分？",
    answerSpecPattern: numberAnswer("分"),
    explanationPattern: "先把四次得分相加，再除以 4，平均分是 {{answer}} 分。",
    variables: { scores: ["76、84、88、92", "81、85、89、93", "70、78、86、94"], answer: [85, 87, 82] },
  },
  {
    id: "data-compare-01", skillCode: "data-compare", domain: "data_statistics",
    difficulty: 3, structureTag: "data-two-condition", answerMode: "choice", readingCard: true,
    stemPattern: "甲组数据是 {{firstSet}}，乙组数据是 {{secondSet}}。要求“平均数更大且波动更小”，哪组符合？A. 甲组  B. 乙组  C. 两组都符合  D. 信息不足",
    answerSpecPattern: choiceAnswer("B"),
    explanationPattern: "同时核对平均水平与数据间距两条信息；乙组的数量关系满足平均数更大、范围更小，所以选 B。",
    variables: { firstSet: ["6、10、14", "12、18、24", "20、30、40"], secondSet: ["10、11、12", "18、19、20", "30、31、32"] },
  },
  {
    id: "data-possibility-01", skillCode: "possibility", domain: "data_statistics",
    difficulty: 2, structureTag: "simple-probability", answerMode: "choice",
    stemPattern: "袋中有 {{red}} 个红球、{{blue}} 个蓝球和 {{green}} 个绿球。任取一个，哪种颜色最可能出现？A. 红  B. 蓝  C. 绿  D. 三种一样",
    answerSpecPattern: choiceAnswer("B"),
    explanationPattern: "比较三种球的数量，蓝球最多，所以取到蓝球的可能性最大。",
    variables: { red: [3, 5, 4], blue: [7, 9, 8], green: [5, 6, 3] },
  },
  {
    id: "data-table-02", skillCode: "data-table", domain: "data_statistics",
    difficulty: 1, structureTag: "table-multi-read", answerMode: "written", readingCard: true,
    stemPattern: "阅读记录：甲组 {{aMorning}} 人上午参加、{{aAfternoon}} 人下午参加；乙组 {{bMorning}} 人上午参加、{{bAfternoon}} 人下午参加。两组下午参加的总人数是多少人？",
    answerSpecPattern: numberAnswer("人"),
    explanationPattern: "题目只要下午这一列的信息，数量关系是 {{aAfternoon}} + {{bAfternoon}} = {{answer}} 人。",
    variables: { aMorning: [8, 11, 14], aAfternoon: [7, 10, 12], bMorning: [9, 12, 16], bAfternoon: [6, 13, 15], answer: [13, 23, 27] },
  },
  {
    id: "data-table-03", skillCode: "data-table", domain: "data_statistics",
    difficulty: 3, structureTag: "table-multi-read", answerMode: "written", readingCard: true,
    stemPattern: "阅读记录：甲组 {{aMorning}} 人上午参加、{{aAfternoon}} 人下午参加；乙组 {{bMorning}} 人上午参加、{{bAfternoon}} 人下午参加。两组下午参加的总人数是多少人？",
    answerSpecPattern: numberAnswer("人"),
    explanationPattern: "题目只要下午这一列的信息，数量关系是 {{aAfternoon}} + {{bAfternoon}} = {{answer}} 人。",
    variables: { aMorning: [21, 25, 30], aAfternoon: [18, 22, 27], bMorning: [19, 24, 28], bAfternoon: [16, 21, 25], answer: [34, 43, 52] },
  },
  {
    id: "data-bar-02", skillCode: "data-bar", domain: "data_statistics",
    difficulty: 2, structureTag: "bar-compare", answerMode: "written", readingCard: true,
    stemPattern: "条形图文字记录显示：一班回收 {{first}} 千克，二班回收 {{second}} 千克，三班回收 {{third}} 千克。最多的班比最少的班多多少千克？",
    answerSpecPattern: numberAnswer("千克"),
    explanationPattern: "先从三条信息中找最大值和最小值，再相减，数量关系得到 {{answer}} 千克。",
    variables: { first: [32, 45, 28], second: [27, 51, 36], third: [40, 39, 44], answer: [13, 12, 16] },
  },
  {
    id: "data-bar-03", skillCode: "data-bar", domain: "data_statistics",
    difficulty: 3, structureTag: "bar-compare", answerMode: "written", readingCard: true,
    stemPattern: "条形图文字记录显示：一班回收 {{first}} 千克，二班回收 {{second}} 千克，三班回收 {{third}} 千克。最多的班比最少的班多多少千克？",
    answerSpecPattern: numberAnswer("千克"),
    explanationPattern: "先从三条信息中找最大值和最小值，再相减，数量关系得到 {{answer}} 千克。",
    variables: { first: [68, 73, 81], second: [55, 80, 64], third: [92, 69, 75], answer: [37, 11, 17] },
  },
  {
    id: "data-line-02", skillCode: "data-line", domain: "data_statistics",
    difficulty: 3, structureTag: "line-change", answerMode: "written", readingCard: true,
    stemPattern: "折线记录中，周一为 {{monday}} 页，周二为 {{tuesday}} 页，周三为 {{wednesday}} 页。周一到周三一共增加了多少页？",
    answerSpecPattern: numberAnswer("页"),
    explanationPattern: "问题比较起点和终点，不必把每天变化相加；用周三信息减周一信息，得到 {{answer}} 页。",
    variables: { monday: [34, 42, 51], tuesday: [39, 48, 57], wednesday: [46, 55, 66], answer: [12, 13, 15] },
  },
  {
    id: "data-average-02", skillCode: "data-average", domain: "data_statistics",
    difficulty: 2, structureTag: "average", answerMode: "written",
    stemPattern: "四次练习得分依次为 {{scores}} 分，平均分是多少分？",
    answerSpecPattern: numberAnswer("分"),
    explanationPattern: "先把四次得分相加，再除以 4，平均分是 {{answer}} 分。",
    variables: { scores: ["72、78、84、90", "80、82、86、88", "65、75、85、95"], answer: [81, 84, 80] },
  },
  {
    id: "data-average-03", skillCode: "data-average", domain: "data_statistics",
    difficulty: 4, structureTag: "average", answerMode: "written",
    stemPattern: "四次练习得分依次为 {{scores}} 分，平均分是多少分？",
    answerSpecPattern: numberAnswer("分"),
    explanationPattern: "先把四次得分相加，再除以 4，平均分是 {{answer}} 分。",
    variables: { scores: ["91、87、83、79", "68、76、88、96", "74、82、90、98"], answer: [85, 82, 86] },
  },
  {
    id: "data-compare-02", skillCode: "data-compare", domain: "data_statistics",
    difficulty: 4, structureTag: "data-two-condition", answerMode: "choice", readingCard: true,
    stemPattern: "甲组数据是 {{firstSet}}，乙组数据是 {{secondSet}}。要求“平均数更大且波动更小”，哪组符合？A. 甲组  B. 乙组  C. 两组都符合  D. 信息不足",
    answerSpecPattern: choiceAnswer("B"),
    explanationPattern: "同时核对平均水平与数据间距两条信息；乙组的数量关系满足平均数更大、范围更小，所以选 B。",
    variables: { firstSet: ["5、12、19", "15、20、25", "30、40、50"], secondSet: ["12、13、14", "20、21、22", "45、46、47"] },
  },
  {
    id: "data-possibility-02", skillCode: "possibility", domain: "data_statistics",
    difficulty: 3, structureTag: "simple-probability", answerMode: "choice",
    stemPattern: "袋中有 {{red}} 个红球、{{blue}} 个蓝球和 {{green}} 个绿球。任取一个，哪种颜色最可能出现？A. 红  B. 蓝  C. 绿  D. 三种一样",
    answerSpecPattern: choiceAnswer("B"),
    explanationPattern: "比较三种球的数量，蓝球最多，所以取到蓝球的可能性最大。",
    variables: { red: [8, 6, 9], blue: [11, 10, 12], green: [5, 8, 7] },
  },

  {
    id: "app-price-01", skillCode: "price-model", domain: "application_modeling",
    difficulty: 2, structureTag: "unit-price", answerMode: "written", readingCard: true,
    stemPattern: "每本练习册 {{price}} 元，买 {{count}} 本一共需要多少元？",
    answerSpecPattern: numberAnswer("元"),
    explanationPattern: "总价等于单价乘数量，{{price}} × {{count}} = {{answer}} 元。",
    variables: { price: [6, 8, 12], count: [4, 5, 7], answer: [24, 40, 84] },
  },
  {
    id: "app-price-02", skillCode: "price-model", domain: "application_modeling",
    difficulty: 3, structureTag: "price-compare", answerMode: "written", readingCard: true,
    stemPattern: "商店甲每包 {{aCount}} 支笔，售价 {{aPrice}} 元；商店乙每包 {{bCount}} 支，售价 {{bPrice}} 元。各买到 {{target}} 支时，选择更省的方案可少付多少元？",
    answerSpecPattern: numberAnswer("元"),
    explanationPattern: "先根据每包数量信息算各需几包，再比较两种总价；数量关系表明可少付 {{answer}} 元。",
    variables: { aCount: [4, 5, 6], aPrice: [10, 12, 15], bCount: [6, 10, 9], bPrice: [14, 22, 21], target: [12, 20, 18], answer: [2, 4, 3] },
  },
  {
    id: "app-distance-01", skillCode: "distance-model", domain: "application_modeling",
    difficulty: 2, structureTag: "speed-time-distance", answerMode: "written",
    stemPattern: "自行车每小时行 {{speed}} 千米，连续骑 {{hours}} 小时，行程是多少千米？",
    answerSpecPattern: numberAnswer("千米"),
    explanationPattern: "路程等于速度乘时间，{{speed}} × {{hours}} = {{answer}} 千米。",
    variables: { speed: [12, 15, 18], hours: [3, 4, 5], answer: [36, 60, 90] },
  },
  {
    id: "app-distance-02", skillCode: "distance-model", domain: "application_modeling",
    difficulty: 3, structureTag: "distance-multi-leg", answerMode: "written", readingCard: true,
    stemPattern: "小车先以每小时 {{firstSpeed}} 千米行 {{firstHours}} 小时，休息 {{rest}} 分钟后，再以每小时 {{secondSpeed}} 千米行 {{secondHours}} 小时。全程行驶多少千米？",
    answerSpecPattern: numberAnswer("千米"),
    explanationPattern: "休息时间不是行驶信息；分别算两段路程再相加，数量关系得到 {{answer}} 千米。",
    variables: { firstSpeed: [40, 45, 50], firstHours: [2, 3, 2], rest: [20, 30, 15], secondSpeed: [35, 40, 55], secondHours: [1, 2, 3], answer: [115, 215, 265] },
  },
  {
    id: "app-work-01", skillCode: "work-model", domain: "application_modeling",
    difficulty: 2, structureTag: "work-rate", answerMode: "written",
    stemPattern: "一台机器每分钟装 {{rate}} 个零件，工作 {{minutes}} 分钟，一共装多少个？",
    answerSpecPattern: numberAnswer("个"),
    explanationPattern: "总量等于每分钟数量乘时间，得到 {{answer}} 个。",
    variables: { rate: [8, 12, 15], minutes: [6, 7, 9], answer: [48, 84, 135] },
  },
  {
    id: "app-work-02", skillCode: "work-model", domain: "application_modeling",
    difficulty: 3, structureTag: "work-together", answerMode: "written", readingCard: true,
    stemPattern: "甲每分钟整理 {{firstRate}} 本，乙每分钟整理 {{secondRate}} 本。两人同时工作 {{minutes}} 分钟，桌上原有 {{extra}} 本备用记录册不需整理。实际整理多少本？",
    answerSpecPattern: numberAnswer("本"),
    explanationPattern: "备用记录册是无效信息；把两人的效率相加后乘时间，数量关系得到 {{answer}} 本。",
    variables: { firstRate: [5, 7, 8], secondRate: [3, 4, 6], minutes: [6, 8, 9], extra: [12, 20, 15], answer: [48, 88, 126] },
  },
  {
    id: "app-ratio-01", skillCode: "ratio-model", domain: "application_modeling",
    difficulty: 2, structureTag: "ratio-share", answerMode: "written",
    stemPattern: "红、蓝卡片数量比是 {{redPart}}:{{bluePart}}，共有 {{total}} 张。红卡片有多少张？",
    answerSpecPattern: numberAnswer("张"),
    explanationPattern: "总份数是 {{redPart}} + {{bluePart}}，红卡片占其中 {{redPart}} 份，得到 {{answer}} 张。",
    variables: { redPart: [2, 3, 5], bluePart: [3, 4, 7], total: [25, 42, 72], answer: [10, 18, 30] },
  },
  {
    id: "app-ratio-02", skillCode: "ratio-model", domain: "application_modeling",
    difficulty: 3, structureTag: "ratio-adjust", answerMode: "written", readingCard: true,
    stemPattern: "甲、乙两杯果汁原有体积比 {{first}}:{{second}}，总量 {{total}} 毫升。喝掉甲杯 {{drink}} 毫升后，甲杯还剩多少毫升？",
    answerSpecPattern: numberAnswer("毫升"),
    explanationPattern: "先按比例信息求甲杯原有体积，再减去喝掉的量；数量关系得到 {{answer}} 毫升。",
    variables: { first: [2, 3, 5], second: [3, 5, 7], total: [500, 640, 720], drink: [40, 60, 75], answer: [160, 180, 225] },
  },
  {
    id: "app-percent-01", skillCode: "percent-model", domain: "application_modeling",
    difficulty: 3, structureTag: "percent-of", answerMode: "written",
    stemPattern: "一件文具原价 {{original}} 元，按 {{percent}}% 计算折后价，折后是多少元？",
    answerSpecPattern: numberAnswer("元"),
    explanationPattern: "折后价等于原价乘 {{percent}}%，结果是 {{answer}} 元。",
    variables: { original: [80, 120, 250], percent: [75, 80, 60], answer: [60, 96, 150] },
  },
  {
    id: "app-percent-02", skillCode: "percent-model", domain: "application_modeling",
    difficulty: 3, structureTag: "percent-two-stage", answerMode: "written", readingCard: true,
    stemPattern: "水箱原有 {{total}} 升水，上午用去 {{morning}}%，下午又用去原有总量的 {{afternoon}}%。还剩多少升？",
    answerSpecPattern: numberAnswer("升"),
    explanationPattern: "两次百分比都以原有总量为基准；先合并有效信息，再算剩余比例，数量关系得到 {{answer}} 升。",
    variables: { total: [200, 300, 500], morning: [25, 20, 30], afternoon: [15, 35, 10], answer: [120, 135, 300] },
  },
  {
    id: "app-multi-step-01", skillCode: "multi-step-model", domain: "application_modeling",
    difficulty: 3, structureTag: "multi-step-plan", answerMode: "written", readingCard: true,
    stemPattern: "学校买来 {{boxes}} 箱纸，每箱 {{perBox}} 包。先给低年级 {{first}} 包，再把剩下的平均分给 {{classes}} 个班，每班多少包？",
    answerSpecPattern: numberAnswer("包"),
    explanationPattern: "先根据箱数与每箱信息求总量，再减去已分出的数量，最后平均分；数量关系得到 {{answer}} 包。",
    variables: { boxes: [6, 8, 10], perBox: [12, 15, 18], first: [24, 30, 45], classes: [4, 6, 9], answer: [12, 15, 15] },
  },
  {
    id: "app-multi-step-02", skillCode: "multi-step-model", domain: "application_modeling",
    difficulty: 4, structureTag: "multi-step-reverse", answerMode: "written", readingCard: true,
    stemPattern: "一批书先借出总数的 {{fraction}}，又归还 {{returned}} 本，此时有 {{remaining}} 本。原来共有多少本？",
    answerSpecPattern: numberAnswer("本"),
    explanationPattern: "归还前剩下 {{remaining}} - {{returned}} 本，对应原总数未借出的部分；逆向建立数量关系可得 {{answer}} 本。",
    variables: { fraction: ["1/4", "2/5", "3/8"], returned: [15, 24, 18], remaining: [75, 84, 93], answer: [80, 100, 120] },
  },
  {
    id: "app-extra-info-01", skillCode: "extra-information", domain: "application_modeling",
    difficulty: 3, structureTag: "extra-info-filter", answerMode: "written", readingCard: true,
    stemPattern: "图书角有故事书 {{stories}} 本、科普书 {{science}} 本，书架高 {{height}} 厘米。今天借出故事书 {{borrowed}} 本。故事书还剩多少本？",
    answerSpecPattern: numberAnswer("本"),
    explanationPattern: "问题只涉及故事书；科普书数量和书架高度都是无效信息，数量关系是 {{stories}} - {{borrowed}} = {{answer}} 本。",
    variables: { stories: [86, 120, 145], science: [42, 65, 78], height: [90, 105, 120], borrowed: [27, 38, 56], answer: [59, 82, 89] },
  },
  {
    id: "app-extra-info-02", skillCode: "extra-information", domain: "application_modeling",
    difficulty: 4, structureTag: "extra-info-model", answerMode: "written", readingCard: true,
    stemPattern: "研学队有 {{students}} 名学生和 {{teachers}} 名教师，大巴每辆坐 {{capacity}} 人，车程 {{minutes}} 分钟。至少需要多少辆大巴？",
    answerSpecPattern: numberAnswer("辆"),
    explanationPattern: "车程是无效信息；先合并学生和教师人数，再按容量分组，有余数也需一整辆，得到 {{answer}} 辆。",
    variables: { students: [83, 126, 157], teachers: [5, 6, 7], capacity: [30, 44, 50], minutes: [45, 60, 75], answer: [3, 3, 4] },
  },
  {
    id: "app-price-03", skillCode: "price-model", domain: "application_modeling",
    difficulty: 2, structureTag: "unit-price", answerMode: "written", readingCard: true,
    stemPattern: "每本练习册 {{price}} 元，买 {{count}} 本一共需要多少元？",
    answerSpecPattern: numberAnswer("元"),
    explanationPattern: "总价等于单价乘数量，{{price}} × {{count}} = {{answer}} 元。",
    variables: { price: [7, 9, 15], count: [6, 8, 9], answer: [42, 72, 135] },
  },
  {
    id: "app-distance-03", skillCode: "distance-model", domain: "application_modeling",
    difficulty: 3, structureTag: "distance-multi-leg", answerMode: "written", readingCard: true,
    stemPattern: "小车先以每小时 {{firstSpeed}} 千米行 {{firstHours}} 小时，休息 {{rest}} 分钟后，再以每小时 {{secondSpeed}} 千米行 {{secondHours}} 小时。全程行驶多少千米？",
    answerSpecPattern: numberAnswer("千米"),
    explanationPattern: "休息时间不是行驶信息；分别算两段路程再相加，数量关系得到 {{answer}} 千米。",
    variables: { firstSpeed: [36, 48, 55], firstHours: [2, 2, 3], rest: [15, 20, 30], secondSpeed: [42, 35, 40], secondHours: [1, 3, 2], answer: [114, 201, 245] },
  },
  {
    id: "app-work-03", skillCode: "work-model", domain: "application_modeling",
    difficulty: 3, structureTag: "work-together", answerMode: "written", readingCard: true,
    stemPattern: "甲每分钟整理 {{firstRate}} 本，乙每分钟整理 {{secondRate}} 本。两人同时工作 {{minutes}} 分钟，桌上原有 {{extra}} 本备用记录册不需整理。实际整理多少本？",
    answerSpecPattern: numberAnswer("本"),
    explanationPattern: "备用记录册是无效信息；把两人的效率相加后乘时间，数量关系得到 {{answer}} 本。",
    variables: { firstRate: [6, 9, 11], secondRate: [4, 5, 7], minutes: [7, 8, 10], extra: [18, 25, 30], answer: [70, 112, 180] },
  },
  {
    id: "app-ratio-03", skillCode: "ratio-model", domain: "application_modeling",
    difficulty: 3, structureTag: "ratio-share", answerMode: "written",
    stemPattern: "红、蓝卡片数量比是 {{redPart}}:{{bluePart}}，共有 {{total}} 张。红卡片有多少张？",
    answerSpecPattern: numberAnswer("张"),
    explanationPattern: "总份数是 {{redPart}} + {{bluePart}}，红卡片占其中 {{redPart}} 份，得到 {{answer}} 张。",
    variables: { redPart: [3, 4, 7], bluePart: [5, 6, 9], total: [32, 50, 80], answer: [12, 20, 35] },
  },
  {
    id: "app-percent-03", skillCode: "percent-model", domain: "application_modeling",
    difficulty: 3, structureTag: "percent-of", answerMode: "written",
    stemPattern: "一件文具原价 {{original}} 元，按 {{percent}}% 计算折后价，折后是多少元？",
    answerSpecPattern: numberAnswer("元"),
    explanationPattern: "折后价等于原价乘 {{percent}}%，结果是 {{answer}} 元。",
    variables: { original: [90, 160, 240], percent: [80, 75, 65], answer: [72, 120, 156] },
  },
  {
    id: "app-multi-step-03", skillCode: "multi-step-model", domain: "application_modeling",
    difficulty: 3, structureTag: "multi-step-plan", answerMode: "written", readingCard: true,
    stemPattern: "学校买来 {{boxes}} 箱纸，每箱 {{perBox}} 包。先给低年级 {{first}} 包，再把剩下的平均分给 {{classes}} 个班，每班多少包？",
    answerSpecPattern: numberAnswer("包"),
    explanationPattern: "先根据箱数与每箱信息求总量，再减去已分出的数量，最后平均分；数量关系得到 {{answer}} 包。",
    variables: { boxes: [5, 7, 9], perBox: [16, 18, 20], first: [20, 28, 36], classes: [4, 5, 6], answer: [15, 19.6, 24] },
  },
  {
    id: "app-multi-step-04", skillCode: "multi-step-model", domain: "application_modeling",
    difficulty: 4, structureTag: "multi-step-reverse", answerMode: "written", readingCard: true,
    stemPattern: "一批书先借出总数的 {{fraction}}，又归还 {{returned}} 本，此时有 {{remaining}} 本。原来共有多少本？",
    answerSpecPattern: numberAnswer("本"),
    explanationPattern: "归还前剩下 {{remaining}} - {{returned}} 本，对应原总数未借出的部分；逆向建立数量关系可得 {{answer}} 本。",
    variables: { fraction: ["1/5", "1/3", "2/5"], returned: [12, 18, 24], remaining: [76, 72, 84], answer: [80, 81, 100] },
  },
  {
    id: "app-extra-info-03", skillCode: "extra-information", domain: "application_modeling",
    difficulty: 3, structureTag: "extra-info-filter", answerMode: "written", readingCard: true,
    stemPattern: "图书角有故事书 {{stories}} 本、科普书 {{science}} 本，书架高 {{height}} 厘米。今天借出故事书 {{borrowed}} 本。故事书还剩多少本？",
    answerSpecPattern: numberAnswer("本"),
    explanationPattern: "问题只涉及故事书；科普书数量和书架高度都是无效信息，数量关系是 {{stories}} - {{borrowed}} = {{answer}} 本。",
    variables: { stories: [96, 138, 176], science: [55, 72, 90], height: [95, 110, 125], borrowed: [28, 49, 68], answer: [68, 89, 108] },
  },
  {
    id: "app-extra-info-04", skillCode: "extra-information", domain: "application_modeling",
    difficulty: 4, structureTag: "extra-info-model", answerMode: "written", readingCard: true,
    stemPattern: "研学队有 {{students}} 名学生和 {{teachers}} 名教师，大巴每辆坐 {{capacity}} 人，车程 {{minutes}} 分钟。至少需要多少辆大巴？",
    answerSpecPattern: numberAnswer("辆"),
    explanationPattern: "车程是无效信息；先合并学生和教师人数，再按容量分组，有余数也需一整辆，得到 {{answer}} 辆。",
    variables: { students: [91, 118, 146], teachers: [4, 7, 9], capacity: [35, 40, 52], minutes: [50, 65, 80], answer: [3, 4, 3] },
  },

  {
    id: "habit-question-01", skillCode: "read-question", domain: "thinking_habits",
    difficulty: 1, structureTag: "identify-question", answerMode: "choice",
    stemPattern: "题目说“每盒彩笔 {{perBox}} 支，买了 {{boxes}} 盒，还送了 {{gift}} 支”。问题是“一共有多少支”。真正要求的是：A. 每盒数量  B. 盒数  C. 总支数  D. 赠送数量",
    answerSpecPattern: choiceAnswer("C"),
    explanationPattern: "抓住问句“一共有多少支”，目标量是总支数。",
    errorTargets: { incompleteReading: ["A", "B", "D"] },
    variables: { perBox: [6, 8, 12], boxes: [3, 4, 5], gift: [2, 3, 4] },
  },
  {
    id: "habit-question-02", skillCode: "read-question", domain: "thinking_habits",
    difficulty: 2, structureTag: "question-restate", answerMode: "choice", readingCard: true,
    stemPattern: "材料给出甲车 {{first}} 千米、乙车 {{second}} 千米和行驶时间 {{hours}} 小时，问题问“两车路程相差多少”。哪一句重述最准确？A. 求两车总路程  B. 求甲车速度  C. 用两车路程相减  D. 求乙车时间",
    answerSpecPattern: choiceAnswer("C"),
    explanationPattern: "问句中的“相差”决定数量关系是两个路程相减，时间信息在本问中不参与计算。",
    errorTargets: { incompleteReading: ["A", "B", "D"] },
    variables: { first: [120, 165, 210], second: [95, 130, 178], hours: [2, 3, 4] },
  },
  {
    id: "habit-condition-01", skillCode: "find-condition", domain: "thinking_habits",
    difficulty: 1, structureTag: "match-condition", answerMode: "choice",
    stemPattern: "要计算 {{count}} 本书的总价，已知每本 {{price}} 元。必须使用的两个条件是：A. 本数和单价  B. 书架颜色和本数  C. 单价和日期  D. 日期和颜色",
    answerSpecPattern: choiceAnswer("A"),
    explanationPattern: "总价的数量关系是本数乘单价，所以需要本数和单价。",
    variables: { count: [4, 6, 9], price: [7, 10, 12] },
  },
  {
    id: "habit-condition-02", skillCode: "find-condition", domain: "thinking_habits",
    difficulty: 2, structureTag: "condition-gap", answerMode: "choice", readingCard: true,
    stemPattern: "想求长方形面积，材料只给出长 {{length}} 厘米和周长 {{perimeter}} 厘米。下一步最合理的是：A. 直接用长乘周长  B. 先由周长求宽  C. 把两数相加  D. 信息完全无用",
    answerSpecPattern: choiceAnswer("B"),
    explanationPattern: "面积需要长和宽；现有信息可由周长与长推出宽，再建立面积数量关系。",
    variables: { length: [8, 12, 15], perimeter: [26, 38, 50] },
  },
  {
    id: "habit-unit-01", skillCode: "unit-awareness", domain: "thinking_habits",
    difficulty: 1, structureTag: "choose-unit", answerMode: "choice",
    stemPattern: "教室门的高度约为 {{height}}，最合适的单位是：A. 毫米  B. 厘米  C. 米  D. 千米",
    answerSpecPattern: choiceAnswer("C"),
    explanationPattern: "教室门高度通常约 2 米，结合生活范围应选米。",
    variables: { height: [2, 2.1, 2.2] },
  },
  {
    id: "habit-unit-02", skillCode: "unit-awareness", domain: "thinking_habits",
    difficulty: 2, structureTag: "unit-conversion", answerMode: "written", readingCard: true,
    stemPattern: "步道前段长 {{meters}} 米，后段长 {{centimeters}} 厘米。全长是多少米？请写单位。",
    answerSpecPattern: numberAnswer("米"),
    explanationPattern: "先把厘米信息换算成米，再相加；单位统一后的数量关系得到 {{answer}} 米。",
    variables: { meters: [3, 4.5, 6], centimeters: [50, 80, 25], answer: [3.5, 5.3, 6.25] },
  },
  {
    id: "habit-estimate-01", skillCode: "estimate-check", domain: "thinking_habits",
    difficulty: 2, structureTag: "estimate-before-calculate", answerMode: "choice", readingCard: true,
    stemPattern: "准备精算 {{expression}} 前，哪一个范围最合理？A. {{a}}  B. {{b}}  C. {{c}}  D. {{d}}",
    answerSpecPattern: choiceAnswer("B"),
    explanationPattern: "先把各数看成接近的整值，估计数量关系落在 B 的范围，再做精确计算。",
    variables: { expression: ["49 × 21", "198 + 407", "79.8 ÷ 4.1"], a: ["小于 100", "小于 300", "小于 5"], b: ["900 到 1100", "500 到 700", "15 到 25"], c: ["1500 到 1700", "800 到 1000", "40 到 50"], d: ["大于 3000", "大于 1500", "大于 100"] },
  },
  {
    id: "habit-estimate-02", skillCode: "estimate-check", domain: "thinking_habits",
    difficulty: 4, structureTag: "estimate-counterexample", answerMode: "choice", readingCard: true,
    stemPattern: "同学说 {{expression}} 的结果是 {{claim}}。只用数量级判断，哪项最可靠？A. 结果合理  B. 结果明显偏离合理范围  C. 只看个位即可  D. 无法进行任何判断",
    answerSpecPattern: choiceAnswer("B"),
    explanationPattern: "把算式中的数看作邻近整值，合理结果与 {{claim}} 的数量级明显不同，因此应先怀疑计算。",
    variables: { expression: ["402 × 19", "62.5 ÷ 2.5", "995 + 1008"], claim: [760, 250, 20003] },
  },
  {
    id: "habit-check-01", skillCode: "check-strategy", domain: "thinking_habits",
    difficulty: 3, structureTag: "choose-check", answerMode: "choice", readingCard: true,
    stemPattern: "计算 {{expression}} 得到 {{claim}} 后，哪种检查最有说服力？A. 再抄一遍答案  B. 用逆运算还原并比较数量级  C. 只看书写整齐  D. 改用不同单位但不计算",
    answerSpecPattern: choiceAnswer("B"),
    explanationPattern: "逆运算检查结构，估算检查范围；两种证据一起能检验答案而不是重复原步骤。",
    variables: { expression: ["84 - 29", "7.5 × 8", "144 ÷ 12"], claim: [55, 60, 12] },
  },
  {
    id: "habit-check-02", skillCode: "check-strategy", domain: "thinking_habits",
    difficulty: 4, structureTag: "check-evidence", answerMode: "choice", readingCard: true,
    stemPattern: "小安计算原算式 {{original}}，得到答案 {{claim}}。他估算结果范围为 {{range}}，并用逆运算 {{inverse}} 检查。根据这些证据应判断：A. 两项检查都支持答案  B. 只有书写能判断  C. 证据互相矛盾，需重算  D. 不需要检查",
    answerSpecPattern: choiceAnswer("A"),
    explanationPattern: "原答案既落在估算范围内，逆运算信息也还原成功，两条独立证据共同支持结论。",
    variables: {
      original: ["84 - 29", "12.5 × 8", "72 ÷ 9"],
      range: ["50 到 60", "90 到 110", "7 到 9"],
      inverse: ["55 + 29 = 84", "100 ÷ 8 = 12.5", "8 × 9 = 72"],
      claim: [55, 100, 8],
    },
  },
  {
    id: "habit-question-03", skillCode: "read-question", domain: "thinking_habits",
    difficulty: 2, structureTag: "question-restate", answerMode: "choice", readingCard: true,
    stemPattern: "材料给出甲车 {{first}} 千米、乙车 {{second}} 千米和行驶时间 {{hours}} 小时，问题问“两车路程相差多少”。哪一句重述最准确？A. 求两车总路程  B. 求甲车速度  C. 用两车路程相减  D. 求乙车时间",
    answerSpecPattern: choiceAnswer("C"),
    explanationPattern: "问句中的“相差”决定数量关系是两个路程相减，时间信息在本问中不参与计算。",
    errorTargets: { incompleteReading: ["A", "B", "D"] },
    variables: { first: [148, 176, 225], second: [96, 142, 188], hours: [2, 4, 5] },
  },
  {
    id: "habit-condition-03", skillCode: "find-condition", domain: "thinking_habits",
    difficulty: 2, structureTag: "condition-gap", answerMode: "choice", readingCard: true,
    stemPattern: "想求长方形面积，材料只给出长 {{length}} 厘米和周长 {{perimeter}} 厘米。下一步最合理的是：A. 直接用长乘周长  B. 先由周长求宽  C. 把两数相加  D. 信息完全无用",
    answerSpecPattern: choiceAnswer("B"),
    explanationPattern: "面积需要长和宽；现有信息可由周长与长推出宽，再建立面积数量关系。",
    variables: { length: [9, 14, 18], perimeter: [30, 46, 58] },
  },
  {
    id: "habit-unit-03", skillCode: "unit-awareness", domain: "thinking_habits",
    difficulty: 3, structureTag: "unit-conversion", answerMode: "written", readingCard: true,
    stemPattern: "步道前段长 {{meters}} 米，后段长 {{centimeters}} 厘米。全长是多少米？请写单位。",
    answerSpecPattern: numberAnswer("米"),
    explanationPattern: "先把厘米信息换算成米，再相加；单位统一后的数量关系得到 {{answer}} 米。",
    variables: { meters: [7, 8.5, 10], centimeters: [40, 75, 60], answer: [7.4, 9.25, 10.6] },
  },
  {
    id: "habit-estimate-03", skillCode: "estimate-check", domain: "thinking_habits",
    difficulty: 3, structureTag: "estimate-before-calculate", answerMode: "choice", readingCard: true,
    stemPattern: "准备精算 {{expression}} 前，哪一个范围最合理？A. {{a}}  B. {{b}}  C. {{c}}  D. {{d}}",
    answerSpecPattern: choiceAnswer("B"),
    explanationPattern: "先把各数看成接近的整值，估计数量关系落在 B 的范围，再做精确计算。",
    variables: { expression: ["61 × 19", "302 + 198", "84.2 ÷ 4.1"], a: ["小于 500", "小于 300", "小于 5"], b: ["1000 到 1300", "400 到 600", "15 到 25"], c: ["1500 到 1800", "700 到 900", "30 到 40"], d: ["大于 2500", "大于 1200", "大于 100"] },
  },
  {
    id: "habit-estimate-04", skillCode: "estimate-check", domain: "thinking_habits",
    difficulty: 4, structureTag: "estimate-counterexample", answerMode: "choice", readingCard: true,
    stemPattern: "同学说 {{expression}} 的结果是 {{claim}}。只用数量级判断，哪项最可靠？A. 结果合理  B. 结果明显偏离合理范围  C. 只看个位即可  D. 无法进行任何判断",
    answerSpecPattern: choiceAnswer("B"),
    explanationPattern: "把算式中的数看作邻近整值，合理结果与 {{claim}} 的数量级明显不同，因此应先怀疑计算。",
    variables: { expression: ["299 × 21", "88.2 ÷ 2.9", "1205 + 798"], claim: [620, 300, 20003] },
  },
  {
    id: "habit-check-03", skillCode: "check-strategy", domain: "thinking_habits",
    difficulty: 3, structureTag: "choose-check", answerMode: "choice", readingCard: true,
    stemPattern: "计算 {{expression}} 得到 {{claim}} 后，哪种检查最有说服力？A. 再抄一遍答案  B. 用逆运算还原并比较数量级  C. 只看书写整齐  D. 改用不同单位但不计算",
    answerSpecPattern: choiceAnswer("B"),
    explanationPattern: "逆运算检查结构，估算检查范围；两种证据一起能检验答案而不是重复原步骤。",
    variables: { expression: ["96 - 47", "8.4 × 6", "180 ÷ 15"], claim: [49, 50.4, 12] },
  },
];

export const phase2Catalog: ReviewedTemplate[] = catalogInputs.map(reviewed);

const skillDefinitions = {
  "integer-mental": ["整数口算", "number_operations"],
  decimal: ["小数运算", "number_operations"],
  fraction: ["分数运算", "number_operations"],
  "mixed-operations": ["混合运算", "number_operations"],
  "operation-law": ["运算律", "number_operations"],
  estimate: ["估算", "number_operations"],
  "reverse-check": ["逆运算检查", "number_operations"],
  "equation-l1": ["一级方程：等式平衡", "equation_algebra"],
  "equation-l2": ["二级方程：加减", "equation_algebra"],
  "equation-l3": ["三级方程：乘除", "equation_algebra"],
  "equation-l4": ["四级方程：两步", "equation_algebra"],
  "equation-l5": ["五级方程：括号与分式", "equation_algebra"],
  "equation-l6": ["六级方程：建模与检验", "equation_algebra"],
  angle: ["角度关系", "geometry_space"],
  perimeter: ["周长", "geometry_space"],
  area: ["面积", "geometry_space"],
  volume: ["体积", "geometry_space"],
  "composite-geometry": ["组合图形", "geometry_space"],
  spatial: ["空间观察", "geometry_space"],
  "data-table": ["表格阅读", "data_statistics"],
  "data-bar": ["条形图", "data_statistics"],
  "data-line": ["折线图", "data_statistics"],
  "data-average": ["平均数", "data_statistics"],
  "data-compare": ["数据比较", "data_statistics"],
  possibility: ["可能性", "data_statistics"],
  "price-model": ["价格模型", "application_modeling"],
  "distance-model": ["行程模型", "application_modeling"],
  "work-model": ["工程模型", "application_modeling"],
  "ratio-model": ["比与分配", "application_modeling"],
  "percent-model": ["百分数模型", "application_modeling"],
  "multi-step-model": ["多步应用", "application_modeling"],
  "extra-information": ["信息筛选", "application_modeling"],
  "read-question": ["辨认问题", "thinking_habits"],
  "find-condition": ["提取条件", "thinking_habits"],
  "unit-awareness": ["单位意识", "thinking_habits"],
  "estimate-check": ["估算检查", "thinking_habits"],
  "check-strategy": ["检查策略", "thinking_habits"],
} as const satisfies Record<string, readonly [string, LearningDomain]>;

export const phase2Skills = Object.entries(skillDefinitions).map(([code, [name, domain]]) => ({
  id: `skill-${code}`,
  code,
  name,
  domain,
}));
